#!/bin/bash

# Go to root course folder if running outside, but assume we are in "inventory_engine_course"
if [ "$(basename "$PWD")" != "inventory_engine_course" ]; then
    if [ -d "inventory_engine_course" ]; then
        cd inventory_engine_course || exit
    fi
fi

echo "🧹 Clearing out old deep directory structure..."
rm -rf sec01_* sec02_* sec03_* sec04_* sec05_* sec06_* sec07_* sec08_* sec09_*

echo "📂 Creating clean Option A parallel structure..."
mkdir -p notes
mkdir -p src

touch "notes/sec01_intro_and_env.md"
echo "# Sec01 Intro And Env" > "notes/sec01_intro_and_env.md"
echo "" >> "notes/sec01_intro_and_env.md"
touch "notes/sec02_python_refresher.md"
echo "# Sec02 Python Refresher" > "notes/sec02_python_refresher.md"
echo "" >> "notes/sec02_python_refresher.md"
touch "notes/sec03_flask_basics.md"
echo "# Sec03 Flask Basics" > "notes/sec03_flask_basics.md"
echo "" >> "notes/sec03_flask_basics.md"
touch "notes/sec04_docker.md"
echo "# Sec04 Docker" > "notes/sec04_docker.md"
echo "" >> "notes/sec04_docker.md"
touch "notes/sec05_smorest_and_marshmallow.md"
echo "# Sec05 Smorest And Marshmallow" > "notes/sec05_smorest_and_marshmallow.md"
echo "" >> "notes/sec05_smorest_and_marshmallow.md"
touch "notes/sec06_sqlalchemy.md"
echo "# Sec06 Sqlalchemy" > "notes/sec06_sqlalchemy.md"
echo "" >> "notes/sec06_sqlalchemy.md"
touch "notes/sec07_git.md"
echo "# Sec07 Git" > "notes/sec07_git.md"
echo "" >> "notes/sec07_git.md"
touch "notes/sec08_jwt.md"
echo "# Sec08 Jwt" > "notes/sec08_jwt.md"
echo "" >> "notes/sec08_jwt.md"
touch "notes/sec09_deployment.md"
echo "# Sec09 Deployment" > "notes/sec09_deployment.md"
echo "" >> "notes/sec09_deployment.md"

# src/sec01_intro_and_env
mkdir -p "src/sec01_intro_and_env"
touch "src/sec01_intro_and_env/01_introduction_to_course.sh"
echo "#!/bin/bash" > "src/sec01_intro_and_env/01_introduction_to_course.sh"
chmod +x "src/sec01_intro_and_env/01_introduction_to_course.sh"
touch "src/sec01_intro_and_env/02_meet_classmates_and_instructor.sh"
echo "#!/bin/bash" > "src/sec01_intro_and_env/02_meet_classmates_and_instructor.sh"
chmod +x "src/sec01_intro_and_env/02_meet_classmates_and_instructor.sh"
touch "src/sec01_intro_and_env/03_environment_setup.sh"
echo "#!/bin/bash" > "src/sec01_intro_and_env/03_environment_setup.sh"
chmod +x "src/sec01_intro_and_env/03_environment_setup.sh"
touch "src/sec01_intro_and_env/04_how_to_get_started.sh"
echo "#!/bin/bash" > "src/sec01_intro_and_env/04_how_to_get_started.sh"
chmod +x "src/sec01_intro_and_env/04_how_to_get_started.sh"
touch "src/sec01_intro_and_env/05_installing_python_mac.sh"
echo "#!/bin/bash" > "src/sec01_intro_and_env/05_installing_python_mac.sh"
chmod +x "src/sec01_intro_and_env/05_installing_python_mac.sh"
touch "src/sec01_intro_and_env/06_installing_python_windows.sh"
echo "#!/bin/bash" > "src/sec01_intro_and_env/06_installing_python_windows.sh"
chmod +x "src/sec01_intro_and_env/06_installing_python_windows.sh"

# src/sec02_python_refresher
mkdir -p "src/sec02_python_refresher"
touch "src/sec02_python_refresher/01_variables.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/01_variables.py"
chmod +x "src/sec02_python_refresher/01_variables.py"
touch "src/sec02_python_refresher/02_string_formatting.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/02_string_formatting.py"
chmod +x "src/sec02_python_refresher/02_string_formatting.py"
touch "src/sec02_python_refresher/03_getting_user_input.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/03_getting_user_input.py"
chmod +x "src/sec02_python_refresher/03_getting_user_input.py"
touch "src/sec02_python_refresher/04_writing_first_python_app.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/04_writing_first_python_app.py"
chmod +x "src/sec02_python_refresher/04_writing_first_python_app.py"
touch "src/sec02_python_refresher/05_lists_tuples_sets.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/05_lists_tuples_sets.py"
chmod +x "src/sec02_python_refresher/05_lists_tuples_sets.py"
touch "src/sec02_python_refresher/06_lists_tuples_sets_deep_dive.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/06_lists_tuples_sets_deep_dive.py"
chmod +x "src/sec02_python_refresher/06_lists_tuples_sets_deep_dive.py"
touch "src/sec02_python_refresher/07_booleans.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/07_booleans.py"
chmod +x "src/sec02_python_refresher/07_booleans.py"
touch "src/sec02_python_refresher/08_advanced_sets_operations.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/08_advanced_sets_operations.py"
chmod +x "src/sec02_python_refresher/08_advanced_sets_operations.py"
touch "src/sec02_python_refresher/09_if_statements.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/09_if_statements.py"
chmod +x "src/sec02_python_refresher/09_if_statements.py"
touch "src/sec02_python_refresher/10_in_keyword.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/10_in_keyword.py"
chmod +x "src/sec02_python_refresher/10_in_keyword.py"
touch "src/sec02_python_refresher/11_if_statements_with_in.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/11_if_statements_with_in.py"
chmod +x "src/sec02_python_refresher/11_if_statements_with_in.py"
touch "src/sec02_python_refresher/12_loops_for.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/12_loops_for.py"
chmod +x "src/sec02_python_refresher/12_loops_for.py"
touch "src/sec02_python_refresher/13_loops_while.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/13_loops_while.py"
chmod +x "src/sec02_python_refresher/13_loops_while.py"
touch "src/sec02_python_refresher/14_flow_control_loops_ifs.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/14_flow_control_loops_ifs.py"
chmod +x "src/sec02_python_refresher/14_flow_control_loops_ifs.py"
touch "src/sec02_python_refresher/15_list_comprehensions.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/15_list_comprehensions.py"
chmod +x "src/sec02_python_refresher/15_list_comprehensions.py"
touch "src/sec02_python_refresher/16_dictionaries.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/16_dictionaries.py"
chmod +x "src/sec02_python_refresher/16_dictionaries.py"
touch "src/sec02_python_refresher/17_dictionary_comprehensions.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/17_dictionary_comprehensions.py"
chmod +x "src/sec02_python_refresher/17_dictionary_comprehensions.py"
touch "src/sec02_python_refresher/18_destructuring.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/18_destructuring.py"
chmod +x "src/sec02_python_refresher/18_destructuring.py"
touch "src/sec02_python_refresher/19_dictionaries_called_students.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/19_dictionaries_called_students.py"
chmod +x "src/sec02_python_refresher/19_dictionaries_called_students.py"
touch "src/sec02_python_refresher/20_functions.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/20_functions.py"
chmod +x "src/sec02_python_refresher/20_functions.py"
touch "src/sec02_python_refresher/21_function_arguments.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/21_function_arguments.py"
chmod +x "src/sec02_python_refresher/21_function_arguments.py"
touch "src/sec02_python_refresher/22_default_and_keyword_arguments.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/22_default_and_keyword_arguments.py"
chmod +x "src/sec02_python_refresher/22_default_and_keyword_arguments.py"
touch "src/sec02_python_refresher/23_functions_returning_values.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/23_functions_returning_values.py"
chmod +x "src/sec02_python_refresher/23_functions_returning_values.py"
touch "src/sec02_python_refresher/24_functions_deep_dive.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/24_functions_deep_dive.py"
chmod +x "src/sec02_python_refresher/24_functions_deep_dive.py"
touch "src/sec02_python_refresher/25_lambda_functions.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/25_lambda_functions.py"
chmod +x "src/sec02_python_refresher/25_lambda_functions.py"
touch "src/sec02_python_refresher/26_unpacking_args_kwargs.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/26_unpacking_args_kwargs.py"
chmod +x "src/sec02_python_refresher/26_unpacking_args_kwargs.py"
touch "src/sec02_python_refresher/27_oop_in_python.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/27_oop_in_python.py"
chmod +x "src/sec02_python_refresher/27_oop_in_python.py"
touch "src/sec02_python_refresher/28_magic_methods_str_repr.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/28_magic_methods_str_repr.py"
chmod +x "src/sec02_python_refresher/28_magic_methods_str_repr.py"
touch "src/sec02_python_refresher/29_classes_and_objects.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/29_classes_and_objects.py"
chmod +x "src/sec02_python_refresher/29_classes_and_objects.py"
touch "src/sec02_python_refresher/30_classmethod_and_staticmethod.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/30_classmethod_and_staticmethod.py"
chmod +x "src/sec02_python_refresher/30_classmethod_and_staticmethod.py"
touch "src/sec02_python_refresher/31_classmethod_and_staticmethod_deep_dive.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/31_classmethod_and_staticmethod_deep_dive.py"
chmod +x "src/sec02_python_refresher/31_classmethod_and_staticmethod_deep_dive.py"
touch "src/sec02_python_refresher/32_class_inheritance.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/32_class_inheritance.py"
chmod +x "src/sec02_python_refresher/32_class_inheritance.py"
touch "src/sec02_python_refresher/33_class_composition.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/33_class_composition.py"
chmod +x "src/sec02_python_refresher/33_class_composition.py"
touch "src/sec02_python_refresher/34_type_hinting.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/34_type_hinting.py"
chmod +x "src/sec02_python_refresher/34_type_hinting.py"
touch "src/sec02_python_refresher/35_modules_and_imports.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/35_modules_and_imports.py"
chmod +x "src/sec02_python_refresher/35_modules_and_imports.py"
touch "src/sec02_python_refresher/36_absolute_and_relative_imports.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/36_absolute_and_relative_imports.py"
chmod +x "src/sec02_python_refresher/36_absolute_and_relative_imports.py"
touch "src/sec02_python_refresher/37_exceptions.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/37_exceptions.py"
chmod +x "src/sec02_python_refresher/37_exceptions.py"
touch "src/sec02_python_refresher/38_custom_exception_classes.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/38_custom_exception_classes.py"
chmod +x "src/sec02_python_refresher/38_custom_exception_classes.py"
touch "src/sec02_python_refresher/39_first_class_functions.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/39_first_class_functions.py"
chmod +x "src/sec02_python_refresher/39_first_class_functions.py"
touch "src/sec02_python_refresher/40_simple_decorator.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/40_simple_decorator.py"
chmod +x "src/sec02_python_refresher/40_simple_decorator.py"
touch "src/sec02_python_refresher/41_at_syntax_for_decorator.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/41_at_syntax_for_decorator.py"
chmod +x "src/sec02_python_refresher/41_at_syntax_for_decorator.py"
touch "src/sec02_python_refresher/42_mutability_in_python.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/42_mutability_in_python.py"
chmod +x "src/sec02_python_refresher/42_mutability_in_python.py"
touch "src/sec02_python_refresher/43_mutable_default_parameters.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/43_mutable_default_parameters.py"
chmod +x "src/sec02_python_refresher/43_mutable_default_parameters.py"
touch "src/sec02_python_refresher/44_python_basics_quiz.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/44_python_basics_quiz.py"
chmod +x "src/sec02_python_refresher/44_python_basics_quiz.py"
touch "src/sec02_python_refresher/45_keep_in_mind.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/45_keep_in_mind.py"
chmod +x "src/sec02_python_refresher/45_keep_in_mind.py"
touch "src/sec02_python_refresher/46_map_function_explained.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/46_map_function_explained.py"
chmod +x "src/sec02_python_refresher/46_map_function_explained.py"
touch "src/sec02_python_refresher/47_filter_function_explained.py"
echo "#!/usr/bin/env python3" > "src/sec02_python_refresher/47_filter_function_explained.py"
chmod +x "src/sec02_python_refresher/47_filter_function_explained.py"

# src/sec03_flask_basics
mkdir -p "src/sec03_flask_basics"
touch "src/sec03_flask_basics/01_project_summary.py"
echo "#!/usr/bin/env python3" > "src/sec03_flask_basics/01_project_summary.py"
chmod +x "src/sec03_flask_basics/01_project_summary.py"
touch "src/sec03_flask_basics/02_initial_configuration.py"
echo "#!/usr/bin/env python3" > "src/sec03_flask_basics/02_initial_configuration.py"
chmod +x "src/sec03_flask_basics/02_initial_configuration.py"
touch "src/sec03_flask_basics/03_first_endpoint.py"
echo "#!/usr/bin/env python3" > "src/sec03_flask_basics/03_first_endpoint.py"
chmod +x "src/sec03_flask_basics/03_first_endpoint.py"
touch "src/sec03_flask_basics/04_what_is_json.py"
echo "#!/usr/bin/env python3" > "src/sec03_flask_basics/04_what_is_json.py"
chmod +x "src/sec03_flask_basics/04_what_is_json.py"
touch "src/sec03_flask_basics/05_testing_and_interacting.py"
echo "#!/usr/bin/env python3" > "src/sec03_flask_basics/05_testing_and_interacting.py"
chmod +x "src/sec03_flask_basics/05_testing_and_interacting.py"
touch "src/sec03_flask_basics/06_creating_shops.py"
echo "#!/usr/bin/env python3" > "src/sec03_flask_basics/06_creating_shops.py"
chmod +x "src/sec03_flask_basics/06_creating_shops.py"
touch "src/sec03_flask_basics/07_adding_products_to_shops.py"
echo "#!/usr/bin/env python3" > "src/sec03_flask_basics/07_adding_products_to_shops.py"
chmod +x "src/sec03_flask_basics/07_adding_products_to_shops.py"
touch "src/sec03_flask_basics/08_retrieving_specific_shop_and_products.py"
echo "#!/usr/bin/env python3" > "src/sec03_flask_basics/08_retrieving_specific_shop_and_products.py"
chmod +x "src/sec03_flask_basics/08_retrieving_specific_shop_and_products.py"
touch "src/sec03_flask_basics/09_flask_and_rest_api_basics_review.py"
echo "#!/usr/bin/env python3" > "src/sec03_flask_basics/09_flask_and_rest_api_basics_review.py"
chmod +x "src/sec03_flask_basics/09_flask_and_rest_api_basics_review.py"

# src/sec04_docker
mkdir -p "src/sec04_docker"
touch "src/sec04_docker/01_containers_and_images.sh"
echo "#!/bin/bash" > "src/sec04_docker/01_containers_and_images.sh"
chmod +x "src/sec04_docker/01_containers_and_images.sh"
touch "src/sec04_docker/02_download_resources.sh"
echo "#!/bin/bash" > "src/sec04_docker/02_download_resources.sh"
chmod +x "src/sec04_docker/02_download_resources.sh"
touch "src/sec04_docker/03_running_flask_in_container.sh"
echo "#!/bin/bash" > "src/sec04_docker/03_running_flask_in_container.sh"
chmod +x "src/sec04_docker/03_running_flask_in_container.sh"
touch "src/sec04_docker/04_virtualization_quiz.sh"
echo "#!/bin/bash" > "src/sec04_docker/04_virtualization_quiz.sh"
chmod +x "src/sec04_docker/04_virtualization_quiz.sh"

# src/sec05_smorest_and_marshmallow
mkdir -p "src/sec05_smorest_and_marshmallow"
touch "src/sec05_smorest_and_marshmallow/01_adding_dependencies_and_db.py"
echo "#!/usr/bin/env python3" > "src/sec05_smorest_and_marshmallow/01_adding_dependencies_and_db.py"
chmod +x "src/sec05_smorest_and_marshmallow/01_adding_dependencies_and_db.py"
touch "src/sec05_smorest_and_marshmallow/02_adding_new_endpoints.py"
echo "#!/usr/bin/env python3" > "src/sec05_smorest_and_marshmallow/02_adding_new_endpoints.py"
chmod +x "src/sec05_smorest_and_marshmallow/02_adding_new_endpoints.py"
touch "src/sec05_smorest_and_marshmallow/03_testing_endpoints_and_bugfixes.py"
echo "#!/usr/bin/env python3" > "src/sec05_smorest_and_marshmallow/03_testing_endpoints_and_bugfixes.py"
chmod +x "src/sec05_smorest_and_marshmallow/03_testing_endpoints_and_bugfixes.py"
touch "src/sec05_smorest_and_marshmallow/04_running_in_docker_with_autoreload.py"
echo "#!/usr/bin/env python3" > "src/sec05_smorest_and_marshmallow/04_running_in_docker_with_autoreload.py"
chmod +x "src/sec05_smorest_and_marshmallow/04_running_in_docker_with_autoreload.py"
touch "src/sec05_smorest_and_marshmallow/05_blueprints_and_methodviews_shops.py"
echo "#!/usr/bin/env python3" > "src/sec05_smorest_and_marshmallow/05_blueprints_and_methodviews_shops.py"
chmod +x "src/sec05_smorest_and_marshmallow/05_blueprints_and_methodviews_shops.py"
touch "src/sec05_smorest_and_marshmallow/06_blueprints_and_methodviews_products.py"
echo "#!/usr/bin/env python3" > "src/sec05_smorest_and_marshmallow/06_blueprints_and_methodviews_products.py"
chmod +x "src/sec05_smorest_and_marshmallow/06_blueprints_and_methodviews_products.py"
touch "src/sec05_smorest_and_marshmallow/07_marshmallow_schemas.py"
echo "#!/usr/bin/env python3" > "src/sec05_smorest_and_marshmallow/07_marshmallow_schemas.py"
chmod +x "src/sec05_smorest_and_marshmallow/07_marshmallow_schemas.py"
touch "src/sec05_smorest_and_marshmallow/08_data_validation.py"
echo "#!/usr/bin/env python3" > "src/sec05_smorest_and_marshmallow/08_data_validation.py"
chmod +x "src/sec05_smorest_and_marshmallow/08_data_validation.py"
touch "src/sec05_smorest_and_marshmallow/09_smorest_decorators.py"
echo "#!/usr/bin/env python3" > "src/sec05_smorest_and_marshmallow/09_smorest_decorators.py"
chmod +x "src/sec05_smorest_and_marshmallow/09_smorest_decorators.py"
touch "src/sec05_smorest_and_marshmallow/10_download_postman_collection.py"
echo "#!/usr/bin/env python3" > "src/sec05_smorest_and_marshmallow/10_download_postman_collection.py"
chmod +x "src/sec05_smorest_and_marshmallow/10_download_postman_collection.py"
touch "src/sec05_smorest_and_marshmallow/11_testing_after_marshmallow.py"
echo "#!/usr/bin/env python3" > "src/sec05_smorest_and_marshmallow/11_testing_after_marshmallow.py"
chmod +x "src/sec05_smorest_and_marshmallow/11_testing_after_marshmallow.py"
touch "src/sec05_smorest_and_marshmallow/12_smorest_and_marshmallow_review.py"
echo "#!/usr/bin/env python3" > "src/sec05_smorest_and_marshmallow/12_smorest_and_marshmallow_review.py"
chmod +x "src/sec05_smorest_and_marshmallow/12_smorest_and_marshmallow_review.py"

# src/sec06_sqlalchemy
mkdir -p "src/sec06_sqlalchemy"
touch "src/sec06_sqlalchemy/01_pre_lecture_note.py"
echo "#!/usr/bin/env python3" > "src/sec06_sqlalchemy/01_pre_lecture_note.py"
chmod +x "src/sec06_sqlalchemy/01_pre_lecture_note.py"
touch "src/sec06_sqlalchemy/02_introduction_to_sqlalchemy.py"
echo "#!/usr/bin/env python3" > "src/sec06_sqlalchemy/02_introduction_to_sqlalchemy.py"
chmod +x "src/sec06_sqlalchemy/02_introduction_to_sqlalchemy.py"
touch "src/sec06_sqlalchemy/03_product_model_and_shop_model.py"
echo "#!/usr/bin/env python3" > "src/sec06_sqlalchemy/03_product_model_and_shop_model.py"
chmod +x "src/sec06_sqlalchemy/03_product_model_and_shop_model.py"
touch "src/sec06_sqlalchemy/04_one_to_many_relationships.py"
echo "#!/usr/bin/env python3" > "src/sec06_sqlalchemy/04_one_to_many_relationships.py"
chmod +x "src/sec06_sqlalchemy/04_one_to_many_relationships.py"
touch "src/sec06_sqlalchemy/05_flask_sqlalchemy_configuration.py"
echo "#!/usr/bin/env python3" > "src/sec06_sqlalchemy/05_flask_sqlalchemy_configuration.py"
chmod +x "src/sec06_sqlalchemy/05_flask_sqlalchemy_configuration.py"
touch "src/sec06_sqlalchemy/06_inserting_data_into_table.py"
echo "#!/usr/bin/env python3" > "src/sec06_sqlalchemy/06_inserting_data_into_table.py"
chmod +x "src/sec06_sqlalchemy/06_inserting_data_into_table.py"
touch "src/sec06_sqlalchemy/07_finding_models_by_id_or_404.py"
echo "#!/usr/bin/env python3" > "src/sec06_sqlalchemy/07_finding_models_by_id_or_404.py"
chmod +x "src/sec06_sqlalchemy/07_finding_models_by_id_or_404.py"
touch "src/sec06_sqlalchemy/08_updating_models.py"
echo "#!/usr/bin/env python3" > "src/sec06_sqlalchemy/08_updating_models.py"
chmod +x "src/sec06_sqlalchemy/08_updating_models.py"
touch "src/sec06_sqlalchemy/09_retrieving_all_models.py"
echo "#!/usr/bin/env python3" > "src/sec06_sqlalchemy/09_retrieving_all_models.py"
chmod +x "src/sec06_sqlalchemy/09_retrieving_all_models.py"
touch "src/sec06_sqlalchemy/10_deleting_models_with_cascading.py"
echo "#!/usr/bin/env python3" > "src/sec06_sqlalchemy/10_deleting_models_with_cascading.py"
chmod +x "src/sec06_sqlalchemy/10_deleting_models_with_cascading.py"
touch "src/sec06_sqlalchemy/11_testing_database_changes.py"
echo "#!/usr/bin/env python3" > "src/sec06_sqlalchemy/11_testing_database_changes.py"
chmod +x "src/sec06_sqlalchemy/11_testing_database_changes.py"
touch "src/sec06_sqlalchemy/12_sqlalchemy_basics_review.py"
echo "#!/usr/bin/env python3" > "src/sec06_sqlalchemy/12_sqlalchemy_basics_review.py"
chmod +x "src/sec06_sqlalchemy/12_sqlalchemy_basics_review.py"

# src/sec07_git
mkdir -p "src/sec07_git"
touch "src/sec07_git/01_intro_to_git_and_commands.sh"
echo "#!/bin/bash" > "src/sec07_git/01_intro_to_git_and_commands.sh"
chmod +x "src/sec07_git/01_intro_to_git_and_commands.sh"
touch "src/sec07_git/02_branches_and_branch_commands.sh"
echo "#!/bin/bash" > "src/sec07_git/02_branches_and_branch_commands.sh"
chmod +x "src/sec07_git/02_branches_and_branch_commands.sh"
touch "src/sec07_git/03_remote_repositories_and_commands.sh"
echo "#!/bin/bash" > "src/sec07_git/03_remote_repositories_and_commands.sh"
chmod +x "src/sec07_git/03_remote_repositories_and_commands.sh"
touch "src/sec07_git/04_advanced_git_commands.sh"
echo "#!/bin/bash" > "src/sec07_git/04_advanced_git_commands.sh"
chmod +x "src/sec07_git/04_advanced_git_commands.sh"
touch "src/sec07_git/05_rebase_vs_merge_vs_squash.sh"
echo "#!/bin/bash" > "src/sec07_git/05_rebase_vs_merge_vs_squash.sh"
chmod +x "src/sec07_git/05_rebase_vs_merge_vs_squash.sh"
touch "src/sec07_git/06_resolving_merge_conflicts.sh"
echo "#!/bin/bash" > "src/sec07_git/06_resolving_merge_conflicts.sh"
chmod +x "src/sec07_git/06_resolving_merge_conflicts.sh"
touch "src/sec07_git/07_gitignore_necessity.sh"
echo "#!/bin/bash" > "src/sec07_git/07_gitignore_necessity.sh"
chmod +x "src/sec07_git/07_gitignore_necessity.sh"
touch "src/sec07_git/08_git_submodules_and_tips.sh"
echo "#!/bin/bash" > "src/sec07_git/08_git_submodules_and_tips.sh"
chmod +x "src/sec07_git/08_git_submodules_and_tips.sh"
touch "src/sec07_git/09_initializing_git_in_rest_api.sh"
echo "#!/bin/bash" > "src/sec07_git/09_initializing_git_in_rest_api.sh"
chmod +x "src/sec07_git/09_initializing_git_in_rest_api.sh"
touch "src/sec07_git/10_test_git_knowledge.sh"
echo "#!/bin/bash" > "src/sec07_git/10_test_git_knowledge.sh"
chmod +x "src/sec07_git/10_test_git_knowledge.sh"

# src/sec08_jwt
mkdir -p "src/sec08_jwt"
touch "src/sec08_jwt/01_what_is_jwt.py"
echo "#!/usr/bin/env python3" > "src/sec08_jwt/01_what_is_jwt.py"
chmod +x "src/sec08_jwt/01_what_is_jwt.py"
touch "src/sec08_jwt/02_configuring_flask_jwt_extended.py"
echo "#!/usr/bin/env python3" > "src/sec08_jwt/02_configuring_flask_jwt_extended.py"
chmod +x "src/sec08_jwt/02_configuring_flask_jwt_extended.py"
touch "src/sec08_jwt/03_user_model_and_schema.py"
echo "#!/usr/bin/env python3" > "src/sec08_jwt/03_user_model_and_schema.py"
chmod +x "src/sec08_jwt/03_user_model_and_schema.py"
touch "src/sec08_jwt/04_registration_endpoint.py"
echo "#!/usr/bin/env python3" > "src/sec08_jwt/04_registration_endpoint.py"
chmod +x "src/sec08_jwt/04_registration_endpoint.py"
touch "src/sec08_jwt/05_login_endpoint.py"
echo "#!/usr/bin/env python3" > "src/sec08_jwt/05_login_endpoint.py"
chmod +x "src/sec08_jwt/05_login_endpoint.py"
touch "src/sec08_jwt/06_securing_endpoints_via_jwt.py"
echo "#!/usr/bin/env python3" > "src/sec08_jwt/06_securing_endpoints_via_jwt.py"
chmod +x "src/sec08_jwt/06_securing_endpoints_via_jwt.py"
touch "src/sec08_jwt/07_logout_feature.py"
echo "#!/usr/bin/env python3" > "src/sec08_jwt/07_logout_feature.py"
chmod +x "src/sec08_jwt/07_logout_feature.py"
touch "src/sec08_jwt/08_token_refreshing_overview.py"
echo "#!/usr/bin/env python3" > "src/sec08_jwt/08_token_refreshing_overview.py"
chmod +x "src/sec08_jwt/08_token_refreshing_overview.py"
touch "src/sec08_jwt/09_refreshing_tokens_implementation.py"
echo "#!/usr/bin/env python3" > "src/sec08_jwt/09_refreshing_tokens_implementation.py"
chmod +x "src/sec08_jwt/09_refreshing_tokens_implementation.py"
touch "src/sec08_jwt/10_testing_jwt_changes.py"
echo "#!/usr/bin/env python3" > "src/sec08_jwt/10_testing_jwt_changes.py"
chmod +x "src/sec08_jwt/10_testing_jwt_changes.py"
touch "src/sec08_jwt/11_jwt_basics_review.py"
echo "#!/usr/bin/env python3" > "src/sec08_jwt/11_jwt_basics_review.py"
chmod +x "src/sec08_jwt/11_jwt_basics_review.py"

# src/sec09_deployment
mkdir -p "src/sec09_deployment"
touch "src/sec09_deployment/01_downloading_frontend_code.sh"
echo "#!/bin/bash" > "src/sec09_deployment/01_downloading_frontend_code.sh"
chmod +x "src/sec09_deployment/01_downloading_frontend_code.sh"
touch "src/sec09_deployment/02_extracting_and_running_frontend.sh"
echo "#!/bin/bash" > "src/sec09_deployment/02_extracting_and_running_frontend.sh"
chmod +x "src/sec09_deployment/02_extracting_and_running_frontend.sh"
touch "src/sec09_deployment/03_render_web_service_hosting.sh"
echo "#!/bin/bash" > "src/sec09_deployment/03_render_web_service_hosting.sh"
chmod +x "src/sec09_deployment/03_render_web_service_hosting.sh"
touch "src/sec09_deployment/04_running_flask_gunicorn_docker.sh"
echo "#!/bin/bash" > "src/sec09_deployment/04_running_flask_gunicorn_docker.sh"
chmod +x "src/sec09_deployment/04_running_flask_gunicorn_docker.sh"
touch "src/sec09_deployment/05_render_static_sites_frontend.sh"
echo "#!/bin/bash" > "src/sec09_deployment/05_render_static_sites_frontend.sh"
chmod +x "src/sec09_deployment/05_render_static_sites_frontend.sh"
touch "src/sec09_deployment/06_test_finished_production_app.sh"
echo "#!/bin/bash" > "src/sec09_deployment/06_test_finished_production_app.sh"
chmod +x "src/sec09_deployment/06_test_finished_production_app.sh"
touch "src/sec09_deployment/07_test_your_skills.sh"
echo "#!/bin/bash" > "src/sec09_deployment/07_test_your_skills.sh"
chmod +x "src/sec09_deployment/07_test_your_skills.sh"
touch "src/sec09_deployment/08_conclusion_next_steps.sh"
echo "#!/bin/bash" > "src/sec09_deployment/08_conclusion_next_steps.sh"
chmod +x "src/sec09_deployment/08_conclusion_next_steps.sh"

echo "✅ Option A Workspace generated successfully!"
echo "👉 Next step: Run \"git add -A\" and commit your clean new workspace."